# Generated by Django 5.0.3 on 2024-03-28 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
