# Generated by Django 5.0.3 on 2024-03-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_api', '0003_alter_teammember_deletedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='addedAt',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='deletedAt',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
