# Generated by Django 5.0.3 on 2024-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_api', '0005_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profile_pic_src',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
