# Generated by Django 5.0.3 on 2024-04-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_api', '0006_teammember_profile_pic_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin')], default='regular', max_length=15),
        ),
    ]
